from datetime import datetime
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from email import encoders
import os


class EmailTemplate:
    def __init__(self, hod_name: str, report_file_path: str):
        self.hod_name = hod_name
        self.report_file_path = report_file_path

    def _get_current_month_year(self):
        now = datetime.now()
        month_year = now.strftime("%B %Y")
        return month_year

    def create_message(self):
        msg = MIMEMultipart()
        # msg['To'] = self.hod_name
        msg['Subject'] = f"Monthly Interaction Report for {self._get_current_month_year()} 📊"

        body = f"Dear {self.hod_name},\n\nPlease find attached the monthly interaction report for the month of {self._get_current_month_year()}. " \
               f"This report is automatically generated by our system and outlines the communication and engagement " \
               f"between our mentors and students."
        msg.attach(MIMEText(body, 'plain'))
        if self.report_file_path:
            with open(self.report_file_path, 'rb') as attachment_file:
                attachment_payload = MIMEBase('application', 'octet-stream')
                attachment_payload.set_payload(attachment_file.read())
                encoders.encode_base64(attachment_payload)
                attachment_payload.add_header(
                    'Content-Disposition',
                    f'attachment; filename={os.path.basename(self.report_file_path)}',
                )
                msg.attach(attachment_payload)

        return msg
